name: merge-master

on:
  release:
    types:
      - created

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: merge-to-master
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://github.com/MadokaProject/Madoka.git madoka
          cd madoka
          git fetch origin
          git checkout master
          git merge dev
          git push "https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/MadokaProject/Madoka.git"