name: release-please
on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  release-please:
    if: github.repository == 'MadokaProject/test'
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
      - run: echo "${{ steps.release.outputs.version }}"
        if: ${{ steps.release.outputs.release_created }}
