name: test

on:
  push:
    branches: [ release ]
  pull_request:
    types: [ opened ]
  workflow_dispatch:

jobs:
  test:
    if: github.repository == 'MadokaProject/test'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: test1
        run: |
          git clone https://github.com/MadokaProject/test.git
          ls
          pwd
          cd test
          pwd
      - name: test2
        run: |
          ls
          pwd
          cd ./k8s/images/test
          ls
          pwd
          cd -
          ls
          pwd
